"""Writes the translation unit that carries the build's commit id.

Reads Bazel's stable status file (what bazel/workspace_status.bat emitted) and
emits a one-function .cpp.  Kept deliberately forgiving: a build with no .git
directory, or one where the status command failed, must still compile.  The
fallback string is what then reaches the log, which is honest -- the binary
genuinely does not know its commit.
"""

import sys

KEY = "STABLE_RAINGRASP_COMMIT"
FALLBACK = "unknown"


def read_commit(status_path):
    try:
        with open(status_path, "r", encoding="utf-8") as handle:
            for line in handle:
                # Status files are "KEY value", split on the first space only:
                # nothing here contains one, but a value that did would be
                # truncated rather than mangled.
                name, _, value = line.strip().partition(" ")
                if name == KEY and value:
                    return value
    except OSError:
        pass
    return FALLBACK


def main():
    status_path, out_path = sys.argv[1], sys.argv[2]
    commit = read_commit(status_path)

    # The value comes from `git rev-parse --short`, so it is hex and a dash.
    # Quote-escaping it anyway keeps a hand-edited status file from producing
    # a source file that does not compile.
    escaped = commit.replace("\\", "\\\\").replace('"', '\\"')

    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write(
            "// Generated by bazel/write_version.py -- do not edit.\n"
            '#include "src/common/platform/version.hpp"\n'
            "\n"
            "namespace platform::version {\n"
            "\n"
            "const char *commit() {\n"
            '    return "%s";\n'
            "}\n"
            "\n"
            "}  // namespace platform::version\n" % escaped
        )


if __name__ == "__main__":
    main()
